#!/bin/sh
# runit-session
# Copyright (c) 2022 Jovan Lanik

set -f

error() { echo "$0: Error: $1." >&2; exit 1; }

[ "$RUNIT_SESSION" ] && error 'RUNIT_SESSION is already set'

if [ "$XDG_RUNTIME_DIR" ] 
then
	mkdir -p "$XDG_RUNTIME_DIR/runit-session"
	session="$(mktemp -dtp "$XDG_RUNTIME_DIR/runit-session" XXXXXXXXXX)"
else
	session="$(mktemp -dt runit-session.XXXXXXXXXX)"
fi

export RUNIT_SESSION="$session"

[ -r '/etc/runit-session/session' ] && conf='/etc/runit-session/session'
[ -r "$HOME/.config/runit-session/session" ] && conf="$HOME/.config/runit-session/session"
[ -r "$XDG_CONFIG_HOME/runit-session/session" ] && conf="$XDG_CONFIG_HOME/runit-session/session"
[ "$conf" ] || dbus-run-session sway
[ "$conf" ] && . "$conf"

while [ -r "$session/pid" ]; do sleep 1; done
rm -rf "$session" || error "Couldn't remove session directory"
exit 0
