#!/bin/sh
# runit-session
# Copyright (c) 2022 Jovan Lanik

set -f

error() { echo "$0: Error: $1." >&2; exit 1; }

[ "$RUNIT_SESSION" ] || error 'RUNIT_SESSION not set'
session=$RUNIT_SESSION
[ -r "$session/pid" ] && error 'Session is already running'

# start services in user home,
# funny shit can happen if not.
cd || exit 1

# source service script
[ -d '/etc/runit-session' ] && conf='/etc/runit-session'
[ -d "$HOME/.config/runit-session" ] && conf="$HOME/.config/runit-session"
[ -d "$XDG_CONFIG_HOME/runit-session" ] && conf="$XDG_CONFIG_HOME/runit-session"
[ -r "$conf/service" ] || dbus-update-activation-environment --all
[ -r "$conf/service" ] && . "$conf/service"

svdir="$session/service"
mkdir "$svdir"

# link services to svdir inside the session directory.
svname=''
set +f
for service in "$conf"/*/
do
	svname=$(basename "$service")
	mkdir "$svdir/$svname"
	ln -s "$service/"* "$svdir/$svname/"
done
set -f
unset svname

echo $$ > "$session/pid"
exec runsvdir "$svdir"
